package com.peter.importerservice.validator;

public class ValidationErrorCode {

  public enum Common {
    ALREADY_EXIST,
    TOO_SHORT_VALUE,
    TOO_LONG_VALUE,
    INVALID_EMAIL,
    NOT_BLANK,
    NOT_FOUND,
    BAD_FORMAT,
    MIME_TYPE_ERROR,
    EMAIL_ALREADY_USED,
    PASSWORD_ERROR,
    NOT_EDITABLE
  }

  public enum Import {
    CONFIGURATION_ERROR,
    POSITION_USED_TWICE,
    INVALID_FIELD_NAME_FOR_THE_CURRENT_CONFIGURATION;

    public enum User {
      PROFILE_NOT_ALLOWED
    }

    public enum PurchaseOrder {
      INCONSISTENT_FACTORY_NAME,
      INCONSISTENT_ORDER_DATE,
      INCONSISTENT_SHIPMENT_DATE,
    }

    public enum TestsChecklist {
      INCONSISTENT_PRODUCT_CATEGORY_ID,
    }
  }

  public enum Product {
    PRODUCT_IDENTIFIER_ALREADY_USED,
    IDENTIFIER_NOT_FOUND,
    INVALID_GTIN,
    DESCRIPTION_IS_NOT_AN_IDENTIFIER;
  }

  public enum PurchaseOrder {
    TIMELINE_ERROR
  }

  public enum Address {
    COUNTRY_CODE_ERROR,
    ADMINISTRATIVE_AREA_CODE_ERROR,
    COUNTRY_LABEL_ERROR,
    ADMINISTRATIVE_AREA_LABEL_ERROR;
  }

  public enum User {
    EMAIL_ALREADY_USED;

    public enum Role {
      ROLE_NOT_FOUND,
      CANNOT_SET_ROLE,
      ROLE_NEEDED
    }

    public enum InspectorInfo {
      INSPECTOR_INFO_MUST_BE_NULL_FOR_NON_INSPECTOR_USER,
      INSPECTOR_INFO_MUST_NOT_BE_NULL_FOR_INSPECTOR
    }
  }

  public enum Factory {
    FACTORY_NAME,
    CUSTOM_ID,
    REGISTRATION_NUMBER;
  }

  public enum DefectsChecklist {
    INVALID_CLASSIFICATION,
  }

  public enum TestsChecklist {
    INVALID_SAMPLING_TYPE,
    INVALID_RESPONSE_TYPE,
    SAMPLING_SIZE_NOT_EQUAL_INSPECTION_LEVEL,
    SAMPLING_SIZE_NOT_POSITIVE_INTEGER,
    SAMPLING_SIZE_NOT_PERCENTAGE,
    SAMPLING_SIZE_NOT_EMPTY,
    SAMPLING_SIZE_UNIT_NOT_EMPTY,
  }

  public enum QimaPlus {
    INVALID_LAMBDA,
    INVALID_TOKEN,
    INVALID_SIGNATURE,
    INVALID_AUTHENTICATION,
    INVALID_MESSAGE_TYPE
  }

  public enum Inspection {
    QIMA_PLUS_INSPECTION_DPLUS3,
    FACTORY_USER_NOT_VALIDATED,
    INCORRECT_INSPECTOR_ROLE,
    INVALID_INSPECTION_METHOD_INSPECTOR_MATCHING,
    INVALID_SELFPICKING_WORKFLOW
  }

  public enum Checkpoint {
    INVALID_PROVIDED_BY_QIMA_VALUE,
    NO_QIMA_CERT_KEY
  }

  public enum Setting {
    AUTOPILOT_GENERAL_DAYS_BEFORE_SHIPMENT_NOT_NULL,
    AUTOPILOT_DAYS_BEFORE_SHIPMENT_NOT_NULL,
    AUTOPILOT_DAYS_BEFORE_SHIPMENT_ON_INSPECTION_TYPE_GTE_GLOBAL_DAYS_BEFORE_SHIPMENT
  }
}
